### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by zx108** [oddfar/campus#1]
## 版本情况
Campus版本：1.1.2

## 问题描述
基本信息保存时，接口/system/user/profile(method=PUT)请求报错，注解@PutMapping值未指定属性字段name

1. 复现代码
```java
    @PutMapping("个人信息管理-修改")
```

2. 测试涉及到的文件
SysProfileController

## 问题截图
![image](https://github.com/oddfar/campus/assets/55793102/dac46ff7-54dd-4cb0-be8a-f8555cda8001)

**Comment by oddfar** [comment]
请使用新版本
