### ISSUE TITLE
一个新功能

### ISSUE THREAD

**Issue by Crazy-FuQing** [oddfar/campus#16]
首先感谢作者大大开源这么好用的imaotai项目，这是目前我用过的最好用的自动工具，笔芯笔芯

提一个新功能：目前pushplus需要实名了 ，是否可以考虑后续再添加多种通知方式如pushme、邮件、钉钉、企微等等；或者直接通知到自定义webhook 跪求大大回复

**Comment by oddfar** [comment]
你提错仓库了，这边先关了
webhook有人贡献过，不过我还没合并，可以看一下：https://github.com/oddfar/campus-imaotai/pull/330
