### ISSUE TITLE
[bug]: 关于注解@JsonIgnore，序列化问题

### ISSUE THREAD

**Issue by Mika-7** [oddfar/campus#2]
## 版本情况

Campus版本： 1.1.8（最新版）

## 问题描述
初次启动项目，在用户管理-新增用户时，后端返回密码为空。

## 分析
1. 查对应的 `SysUserEntity` 类源码，发现在字段 password上，注解 `@JsonIgnore` 被错误使用。

2. 前端依然使用 JSON 传递用户对象，导致后端反序列化忽略了 password 字段，导致 `SysUserEntity` 中 password 为空
## 解决思路

以下思路仅供参考，如有更好的方案，欢迎一起讨论。
1.  前端使用 form 表单的形式提交参数，而非 json 格式。

2.  或者，取消注解 `@Data`，改成 getter，setter 方法，在 getter 方法上加注解 `@JsonIgnore`，而在 setter 方法上依然使用注解 `@JsonProperty`

**Comment by oddfar** [comment]
V1.1.9刚发布，已解决这问题，删掉了@JsonProperty（之前版本没加这注解，后边脑子抽风了加上了）

**Comment by oddfar** [comment]
感谢大佬发现bug
