### ISSUE TITLE
[bug]:  发送验证码错误

### ISSUE THREAD

**Issue by lsq211** [oddfar/campus#6]
版本情况:

campus-imaotai:1.0.11

campus框架:1.1.9

![image](https://github.com/oddfar/campus/assets/135681573/1f76e5d2-90cc-4b47-a107-584148f3a994)

**Comment by lsq211** [comment]
发送验证码错误

**Comment by oddfar** [comment]
参考一下：https://github.com/oddfar/campus-imaotai/issues/220
